// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase pooler en mode SESSION (port 5432) — supporte DDL pour les migrations Prisma
    // Le mode TRANSACTION (port 6543, pgBouncer) ne supporte PAS les migrations DDL
    url: process.env["SUPABASE_DIRECT_URL"],
  },
});




